CUDA_VISIBLE_DEVICES=1 python main.py \
--evaluate \
--test_data_dir /lmdb/test \
--vis_dir /logs/hanwha/viz_test \
--voc_file /lmdb/korean_vocab.txt \
--voc_type ALLCASES_SYMBOLS \
--workers 15 \
--batch_size 1024 \
--height 64 \
--width 256 \
--arch ResNet_ASTER \
--with_lstm \
--STN_ON \
--max_len 100 \
--beam_width 5 \
--tps_inputsize 32 64 \
--tps_outputsize 32 100 \
--tps_margins 0.05 0.05 \
--stn_activation none \
--num_control_points 20 \
--resume /logs/hanwha/model_best.pth.tar